### ISSUE TITLE
包名和applicationId不一致时报错BaseSplashActivity

### ISSUE THREAD

**Issue by myie9** [xuexiangjys/TemplateAppProject#7]
包名是com.myie9.mouthmask.huawei
applicationId是com.myie9.mouthmask
Didn't find class "com.myie9.mouthmask.R$styleable" on path: DexPathList

请问该怎么解决,谢谢

Process: com.myie9.mouthmask, PID: 3639
    java.lang.NoClassDefFoundError: com/myie9/mouthmask/R$styleable
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:692)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:659)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:543)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:166)
        at com.xuexiang.xui.widget.activity.BaseSplashActivity.initView(BaseSplashActivity.java:39)
        at com.xuexiang.xui.widget.activity.BaseSplashActivity.onCreate(BaseSplashActivity.java:29)
        at android.app.Activity.performCreate(Activity.java:5264)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
        at com.didiglobal.booster.instrument.ActivityThreadCallback.handleMessage(ActivityThreadCallback.java:49)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:5292)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.myie9.mouthmask.R$styleable" on path: DexPathList[[dex file "dalvik.system.DexFile@41ca47d8", zip file "/data/app/com.myie9.mouthmask-1.apk", zip file "/data/data/com.myie9.mouthmask/code_cache/secondary-dexes/com.myie9.mouthmask-1.apk.classes2.zip"],nativeLibraryDirectories=[/data/app-lib/com.myie9.mouthmask-1, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:692) 
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:659) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:543) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:166) 
        at com.xuexiang.xui.widget.activity.BaseSplashActivity.initView(BaseSplashActivity.java:39) 
        at com.xuexiang.xui.widget.activity.BaseSplashActivity.onCreate(BaseSplashActivity.java:29) 
        at android.app.Activity.performCreate(Activity.java:5264) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390) 
        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
        at com.didiglobal.booster.instrument.ActivityThreadCallback.handleMessage(ActivityThreadCallback.java:49) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:5292) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641) 
        at dalvik.system.NativeStart.main(Native Method)

**Comment by xuexiangjys** [comment]
包名必须和applicationId一致,这是基本常识,否则资源文件是根本找不到的
